In [75]:
import pandas as pd 
import numpy as np

In [76]:
df = pd.read_excel('InventoryData.xlsx', index_col=None)
df

,InventoryId,StoreName,City,Area,ProductName,QuantitySold,QuantityAvailable,Cost,RetailPrice
0,1,National Stores,Ouro Branco,9 Springview Point,Chocolate Bar - Smarties,1,11,4873.07,1500.39
1,2,Family Dollar,Gerakaroú,5434 Daystar Circle,Pepper - Red Bell,6,1,3089.77,2095.61
2,3,BJ's Wholesale Club,Radoboj,3 Darwin Drive,Chickensplit Half,10,11,4591.63,364.02
3,4,Ocean State Job Lot,Al Madīd,684 Bunting Lane,Zucchini - Green,3,1,33.13,2111.21
4,5,Ollie's Bargain Outlet,Bo Phloi,50162 John Wall Drive,"Cod - Salted, Boneless",9,3,3750.18,934.82
...,...,...,...,...,...,...,...,...,...
995,996,Walmart,Anserma,7 Roxbury Place,Okra,3,3,2395.99,596.47
996,997,T.J. Maxx,Xinglongjie,9476 Morrow Trail,Pork - Smoked Back Bacon,12,12,4646.21,3477.17
997,998,Burlington Coat Factory,Isangel,3029 Hollow Ridge Place,Flounder - Fresh,9,6,4739.64,2702.02
998,999,Tuesday Morning,Gaya,496 Dapin Hill,Bread - Wheat Baguette,6,6,2311.42,487.96
999,1000,Big Lots,Sexmoan,99 Granby Place,"Soup - Knorr, French Onion",2,2,4712.33,1769.61

In [77]:
from mlxtend.preprocessing import TransactionEncoder
trc = TransactionEncoder()
bs = trc.fit_transform(df['ProductName'].str.split(' - '))
one_hot = pd.DataFrame(bs, columns=trc.columns_mapping_.keys())
one_hot

,1%,10 Thailand,10%,12 Year Old,"12, Paper",12in Dome,12in Rnd Blk,14x20,16,16 Oz And 32 Oz,...,Wine,Wine La Vielle Ferme Cote Du,Wooden Mop Handle,Wyndham Estate Bin 777,Yams,Yogurt,Yoplait,Yukon Jack,Zinfandel Rosenblum,Zucchini
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

# Data cleaning is needed for furthur investigations
- many unique values are duplicated due to data entry inconsistance and difference in store labelings

#### we'll replace ', ' with ' - ' as some of the splitters have used ', ' and then split every row, using ' - ' splitter

In [78]:
def clean(s): 
    for i in range(len(s)): 
        if ' ' in s[i]: 
            s[i] = list(s[i].split(' '))[-1]
    return s

products_clean = df.ProductName.str.replace(', ', ' - ').str.split(' - ').apply(lambda x: clean(x))

#### we need to one hot encode our Products name, so that we'll get to remove the uneccesary data

In [79]:
from mlxtend.preprocessing import TransactionEncoder
trc = TransactionEncoder()
bs = trc.fit_transform( products_clean )
one_hot_clean = pd.DataFrame( bs, columns=trc.columns_mapping_.keys() )
one_hot_clean

,1%,1.36l,1.5lit,10%,10/20,112con,12,125g,12x16,12x473ml,...,Wine,Wrap,Wrpd,X12,Xl,Yams,Yellow,Yogurt,Yoplait,Zucchini
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

### Numerical Columns have to be removed as they are meaningless in our context

In [80]:
non_words = []
for i in one_hot_clean.columns:
    if len(i) <= 2:
        non_words.append(i)


non_letters = []
for i in one_hot_clean.columns:
    if not str.isalpha(i[0]):
        non_letters.append(i)


plurals = {}

for i in one_hot_clean.columns:
    if i[:-1] in one_hot_clean.columns and i[-1]=='s':
        plurals[i] = i[:-1]

#### there are a couple of plurals in our Products, such as both Pork and Porks, we'll merge the Porks with pork

In [81]:
one_hot_clean = one_hot_clean.drop(non_words, axis=1, errors='ignore')
one_hot_clean = one_hot_clean.drop(non_letters, axis=1, errors='ignore')
for i, j in zip(plurals.keys(), plurals.values()): 
    one_hot_clean[j] = one_hot_clean[i] + one_hot_clean[j]
one_hot_clean = one_hot_clean.drop(list(plurals.keys()), axis=1)

one_hot_clean

,Aaa,Aborio,Absolut,Agnolotti,Ale,Alfalfa,Allspice,Almond,Amaretta,Amarula,...,Wieners,Wine,Wrap,Wrpd,X12,Yams,Yellow,Yogurt,Yoplait,Zucchini
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

#### There Are some Sizes and colors in our column set and also some synonyms which need to be merged such as (Untrimmed and Organic)

In [82]:
colors_size = ['Large', 'Medium', 'Small', 'Double', 'Yellow', 'Red', 'Blue', 'Green', 'White']
one_hot_clean = one_hot_clean.drop(colors_size, axis=1, errors='ignore')


one_hot_clean['Organic'] = one_hot_clean['Organic'] + one_hot_clean['Untrimmed'] 
one_hot_clean = one_hot_clean.drop('Untrimmed', axis=1, errors='ignore')

In [86]:
from mlxtend.frequent_patterns import apriori, association_rules

df_apriori_clean = apriori(one_hot_clean, min_support = 0.003, use_colnames = True, verbose = 1)
df_apriori_clean

Processing 8 combinations | Sampling itemset size 4e 32

     support                     itemsets
0      0.003                     (Aborio)
1      0.007                  (Appetizer)
2      0.004                      (Apple)
3      0.003                   (Assorted)
4      0.005                       (Baby)
..       ...                          ...
207    0.003                 (Wine, Rose)
208    0.004               (Sweet, Shell)
209    0.003           (Veal, Tenderloin)
210    0.003       (Beets, Cane, Organic)
211    0.003  (Veal, Organic, Tenderloin)

[212 rows x 2 columns]

In [87]:
df_ar_clean = association_rules(df_apriori_clean, metric = "confidence", min_threshold = 0.4)
df_ar_clean

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(Rice),(Aborio),0.007,0.003,0.003,0.428571,142.857143,0.002979,1.744750
1,(Aborio),(Rice),0.003,0.007,0.003,1.000000,142.857143,0.002979,inf
2,(Apple),(Juice),0.004,0.011,0.003,0.750000,68.181818,0.002956,3.956000
3,(Bacon),(Pork),0.004,0.015,0.004,1.000000,66.666667,0.003940,inf
4,(Bagel),(Presliced),0.006,0.003,0.003,0.500000,166.666667,0.002982,1.994000
5,(Presliced),(Bagel),0.003,0.006,0.003,1.000000,166.666667,0.002982,inf
6,(Base),(Chicken),0.006,0.013,0.003,0.500000,38.461538,0.002922,1.974000
7,(Tail),(Beef),0.006,0.021,0.004,0.666667,31.746032,0.003874,2.937000
8,(Cane),(Beets),0.003,0.005,0.003,1.000000,200.000000,0.002985,inf
9,(Beets),(Cane),0.005,0.003,0.003,0.600000,200.000000,0.002985,2.492500
10,(Beets),(Organic),0.005,0.011,0.003,0.600000,54.545455,0.002945,2.472500
11,(Blk),(Tray),0.003,0.004,0.003,1.000000,250.000000,0.002988,inf
12,(Tray),(Blk),0.004,0.003,0.003,0.750000,250.000000,0.002988,3.988000
13,(Blush),(Sauce),0.003,0.020,0.003,1.000000,50.000000,0.002940,inf
14,(Roll),(Bread),0.007,0.020,0.003,0.428571,21.428571,0.002860,1.715000
15,(Pancake),(Cake),0.004,0.007,0.004,1.000000,142.857143,0.003972,inf
16,(Cake),(Pancake),0.007,0.004,0.004,0.571429,142.857143,0.003972,2.324000
17,(Campbells),(Soup),0.006,0.022,0.004,0.666667,30.303030,0.003868,2.934000
18,(Cane),(Organic),0.003,0.011,0.003,1.000000,90.909091,0.002967,inf
19,(Chili),(Pepper),0.006,0.019,0.003,0.500000,26.315789,0.002886,1.962000
20,(Chili),(Soup),0.006,0.022,0.003,0.500000,22.727273,0.002868,1.956000
21,(Coffee),(Cream),0.007,0.012,0.003,0.428571,35.714286,0.002916,1.729000
22,(Pasta),(Dry),0.013,0.021,0.007,0.538462,25.641026,0.006727,2.121167
23,(Sherry),(Dry),0.004,0.021,0.003,0.750000,35.714286,0.002916,3.916000
24,(Individual),(Muffin),0.009,0.008,0.004,0.444444,55.555556,0.003928,1.785600
25,(Muffin),(Individual),0.008,0.009,0.004,0.500000,55.555556,0.003928,1.982000
26,(Knorr),(Soup),0.005,0.022,0.005,1.000000,45.454545,0.004890,inf
27,(Strawberry),(Lemonade),0.006,0.012,0.003,0.500000,41.666667,0.002928,1.976000
28,(Salad),(Longos),0.003,0.006,0.003,1.000000,166.666667,0.002982,inf
29,(Longos),(Salad),0.006,0.003,0.003,0.500000,166.666667,0.002982,1.994000
30,(Magnotta),(Wine),0.005,0.066,0.004,0.800000,12.121212,0.003670,4.670000
31,(Merlot),(Wine),0.004,0.066,0.004,1.000000,15.151515,0.003736,inf
32,(Oasis),(Mix),0.006,0.015,0.003,0.500000,33.333333,0.002910,1.970000
33,(Olive),(Oil),0.007,0.014,0.004,0.571429,40.816327,0.003902,2.300667
34,(Tenderloin),(Organic),0.006,0.011,0.003,0.500000,45.454545,0.002934,1.978000
35,(Paste),(Primerba),0.007,0.004,0.003,0.428571,107.142857,0.002972,1.743000
36,(Primerba),(Paste),0.004,0.007,0.003,0.750000,107.142857,0.002972,3.972000
37,(Squash),(Pattypan),0.005,0.003,0.003,0.600000,200.000000,0.002985,2.492500
38,(Pattypan),(Squash),0.003,0.005,0.003,1.000000,200.000000,0.002985,inf
39,(Quail),(Whole),0.004,0.016,0.003,0.750000,46.875000,0.002936,3.936000
40,(Riesling),(Wine),0.004,0.066,0.004,1.000000,15.151515,0.003736,inf
41,(Rose),(Wine),0.003,0.066,0.003,1.000000,15.151515,0.002802,inf
42,(Sweet),(Shell),0.005,0.008,0.004,0.800000,100.000000,0.003960,4.960000
43,(Shell),(Sweet),0.008,0.005,0.004,0.500000,100.000000,0.003960,1.990000
44,(Tenderloin),(Veal),0.006,0.013,0.003,0.500000,38.461538,0.002922,1.974000
45,"(Cane, Beets)",(Organic),0.003,0.011,0.003,1.000000,90.909091,0.002967,inf
46,"(Organic, Beets)",(Cane),0.003,0.003,0.003,1.000000,333.333333,0.002991,inf
47,"(Cane, Organic)",(Beets),0.003,0.005,0.003,1.000000,200.000000,0.002985,inf
48,(Beets),"(Cane, Organic)",0.005,0.003,0.003,0.600000,200.000000,0.002985,2.492500
49,(Cane),"(Organic, Beets)",0.003,0.003,0.003,1.000000,333.333333,0.002991,inf
50,"(Veal, Organic)",(Tenderloin),0.003,0.006,0.003,1.000000,166.666667,0.002982,inf
51,"(Veal, Tenderloin)",(Organic),0.003,0.011,0.003,1.000000,90.909091,0.002967,inf
52,"(Tenderloin, Organic)",(Veal),0.003,0.013,0.003,1.000000,76.923077,0.002961,inf
53,(Tenderloin),"(Veal, Organic)",0.006,0.003,0.003,0.500000,166.666667,0.002982,1.994000